
spring:
  data:
    mongodb:
      database: bookhub
      uri: mongodb://localhost:27017
      auto-index-creation: true
  #
  application:
    jwt:
      expiration-time: 3200
      secret: Bookhub_Secret
server:
  port: 5003